import React from 'react'

const page = () => {
  return (
    <div>
      i am about
    </div>
  )
}

export default page

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};
